#!/bin/bash

# This script takes snapshots of the files/data directory on google cloud instances

# To setup as a cron job:
# 0 9 * * * /var/lib/spida/snapshot.sh $disk-id

DT=`date +%Y%m%d`
DT2=`date -d'-1 week' +%Y%m%d`
name="$1"
zone="$2"
if [[ "$zone" = "" ]]; then
	zone="us-central1-a"
fi

sudo sync
sudo fsfreeze -f /apps/spidamin
gcloud compute disks snapshot $name --snapshot-names $name-v$DT --no-user-output-enabled --zone $zone
sudo fsfreeze -u /apps/spidamin
LIST__STD_ERR=$(gcloud compute snapshots list --filter="name=('$name-v$DT2')" 2>&1 > /dev/null)
if [[ "$LIST__STD_ERR" == "" ]]; then
	gcloud compute snapshots delete $name-v$DT2 --no-user-output-enabled -q
fi
