#!/bin/bash

dockerComposeFile=/var/lib/spida/docker-compose.yml

read -p "Docker username: " username
read -p "Docker email: " email
read  -s -p "Docker password: " dockerPassword

sudo docker login -u $username -e $email -p $dockerPassword

sudo docker-compose -f $dockerComposeFile stop
sudo docker-compose -f $dockerComposeFile rm --force
sudo docker-compose -f $dockerComposeFile pull
sudo docker-compose -f $dockerComposeFile up -d

sudo docker logout