#!/bin/bash

####################################################################################
# Vars
####################################################################################
dockerEmail=""
dockerUsername=""
dockerPassword=""
dockerComposeFile=/etc/spida/docker-compose.yml

####################################################################################
# Parses Args
####################################################################################
function parseCommandLineArguments() {
  while [ $# -gt 0 ]
  do
      case "$1" in
          --username)  dockerUsername="$2"; shift;;
          --email)  dockerEmail="$2"; shift;;
          --password)  dockerPassword="$2"; shift;;
          --composefile)  dockerComposeFile="$2"; shift;;

          *)
              echo >&2 \
              "usage: $0 [option value]
                Options:
                  --username          dockerhub username (will prompt for username if argument is not passed)
                  --email             dockerhub email (will prompt for email if argument is not passed)
                  --password          dockerhub password (will prompt for password if argument is not passed)
                  --composefile       the location of the docker compose file (defaults to $dockerComposeFile)
              "
              exit 1;;
          *)  break;; # terminate while loop
      esac
      shift
  done
}

####################################################################################
# Logs in to Docker
####################################################################################
function dockerLogin() {
  if [[ "$dockerUsername" = "" ]]; then
    read -p "Docker username: " dockerUsername
  fi

  if [[ "$dockerEmail" = "" ]]; then
    read -p "Docker email: " dockerEmail
  fi

  if [[ "$dockerPassword" = "" ]]; then
  	read  -s -p "Docker password: " dockerPassword
  fi

  sudo docker login -u $dockerUsername -e $dockerEmail -p $dockerPassword
 
  if [ $? -ne 0 ]; then
    echo "login failed, exiting."
    exit 1
  fi

  
}

parseCommandLineArguments $@
dockerLogin

echo "stopping docker containers..."
sudo docker-compose -f $dockerComposeFile stop
echo "removing old docker containers..."
sudo docker-compose -f $dockerComposeFile rm --force
echo "updating docker containers..."
sudo docker-compose -f $dockerComposeFile pull
echo "starting new docker containers..."
sudo docker-compose -f $dockerComposeFile up -d
echo "removing old docker images"
sudo docker rmi $(sudo docker images -q --filter 'dangling=true')
sudo docker logout
